### model
model_name_or_path: /code/table-sft/saves/mistral-finetune/experiment-11000-mistral-lr-5.0e-7-tablellm_train/checkpoint-13602

### method
finetuning_type: full

### dataset
task_dir: /code/LLaMA-Factory/evaluation/
task: gpqa_test  
template: fewshot
lang: en
n_shot: 0

### output
save_dir: /code/table-sft/saves/mistral-finetune/experiment-11000-mistral-lr-5.0e-7-tablellm_train/checkpoint-13602/evaluations/gpqa

### eval
batch_size: 4
